ServerEvents.recipes(event => {
    event.remove({ output: 'gtceu:hardtack_wire_cutter' })
    event.remove({ output: 'gtceu:iron_wire_cutter' })
    event.remove({ output: '#gtceu:scythes' })
    event.remove({ output: '#gtceu:tools' })

    event.remove({type: 'create:mixing'})
    event.remove({type: 'create:crushing'})
    event.remove({type: 'create:pressing'})
    event.remove({type: 'create:milling'})
    event.remove({type: 'create:compacting'})
    event.remove({type: 'create:sawing'})
    event.remove({type: 'create:sequenced_assembly'})
    event.remove({type: 'create:splashing'})
    event.remove({type: 'create:haunting'})
    event.remove({type: 'create:draining'})
    event.remove({type: 'create:filling'})
    event.remove({type: 'create:deploying'})
    event.remove({type: 'create:mechanical_crafting'})
})
