ServerEvents.recipes(event => {
    const toolMats = ["hardtack", "iron", "diamond"]
    toolMats.forEach(mat => {
        event.remove({ output: "gtceu:"+ mat + "_drill_head"})
        event.remove({ output: "gtceu:"+ mat + "_screwdriver_tip"})
        event.remove({ output: "gtceu:"+ mat + "_wire_cutter_head"})
        event.remove({ output: "gtceu:"+ mat + "_chainsaw_head"})
        event.remove({ output: "gtceu:"+ mat + "_wrench_tip"})
    })
    event.remove({ output: "gtceu:hardtack_wrench"})

    event.remove({type: 'create:mixing'})
    event.remove({type: 'create:crushing'})
    event.remove({type: 'create:pressing'})
    event.remove({type: 'create:milling'})
    event.remove({type: 'create:compacting'})
    event.remove({type: 'create:sawing'})
    event.remove({type: 'create:sequenced_assembly'})
    event.remove({type: 'create:splashing'})
    event.remove({type: 'create:haunting'})
    event.remove({type: 'create:draining'})
    event.remove({type: 'create:filling'})
    event.remove({type: 'create:deploying'})
    event.remove({type: 'create:mechanical_crafting'})
})
